version: "3"

services:
  workspace:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    environment:
    - POSTGRES_HOST=database
    - POSTGRES_PORT=5432
    - POSTGRES_DB=polling_db
    - POSTGRES_USER=polling
    - POSTGRES_PASSWORD=pollingpassword
    - API_PORT=3000
    - LOG_LEVEL=6
    command: /bin/zsh -c "while sleep 1000; do :; done"
  database:
    image: postgres:14
    restart: unless-stopped
    environment:
      - POSTGRES_DB=polling_db
      - POSTGRES_USER=polling
      - POSTGRES_PASSWORD=pollingpassword
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432


volumes:
  postgres-data: